---
title: "Economic Connectedness"
author: "Daniel Cho"
format: html
execute:
  echo: false

---


```{r}
#| message: false
library(tidyverse)
```

```{r}
#| message: false
x <- read_csv("data/social_capital_county.csv", show_col_types = FALSE)

x |>
  drop_na() |>
  select(county_name, pop2018, ec_county) |>
  mutate(state = substring(county_name, first = regexpr(", ", county_name)+1)) |>
  summarize(.by = state, state_population = sum(pop2018), avg_county_ec = mean(ec_county)) |>
  ggplot(aes(x = state_population, y = avg_county_ec)) +
  scale_x_log10(breaks = c(1000000, 10000000), labels = scales::comma) + 
  geom_point() + geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Economic Connectedness and Population in US States", 
       subtitle = "Bigger states have counties with lower average economic connectedness",
       x = "State Population", y = "Average County Economic Connectedness", caption = "Data: Opportunity Insights")
```
```{r}
#str_replace(county_name, ".*, ", "")
#str, pattern, replacement 

```

